fix for duplicate asset error app.css
|error MSB4018:
      The "DiscoverPrecompressedAssets" task failed unexpectedly.
      System.ArgumentException: An item with the same key has already been added.